/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.convert.package1;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int mylogo=0x7f020000;
    }
    public static final class id {
        public static final int button=0x7f050001;
        public static final int editText=0x7f050000;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
    public static final class string {
        public static final int calculate=0x7f040002;
        public static final int myApplicationName=0x7f040000;
        public static final int yes=0x7f040001;
    }
}
